apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    run: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: quang1/udagram-reverseproxy:v2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always